M48
; DRILL file {KiCad 9.0.1} date 2025-05-12T23:39:01+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-12T23:39:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X100.0Y-89.0
T2
X91.057Y-93.75
X111.857Y-93.75
M30
